"""
Django settings for sgea project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-jxmcqg)h2tf#o3nbp^^!vla_st14j$uk!sd+%*whxiy)i1z_xa'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'sgea_app',
    'rest_framework',
    'rest_framework.authtoken',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'sgea.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / 'sgea_app' / 'templates',  # Diretório principal de templates
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media',  # Para usar {{ MEDIA_URL }}
                'django.template.context_processors.static',  # Para usar {{ STATIC_URL }}
            ],
        },
    },
]

WSGI_APPLICATION = 'sgea.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 8,  # Mínimo 8 caracteres conforme requisito
        }
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

# Configuração para Português do Brasil
LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'

# Diretórios onde o Django procura arquivos estáticos durante desenvolvimento
STATICFILES_DIRS = [
    BASE_DIR / 'sgea_app' / 'static',
]

# Diretório onde os arquivos estáticos serão coletados para produção
STATIC_ROOT = BASE_DIR / 'staticfiles'


# Media files (Uploads - Banners de eventos, etc)
# https://docs.djangoproject.com/en/5.2/topics/files/

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Configurações de upload de arquivos
FILE_UPLOAD_MAX_MEMORY_SIZE = 5242880  # 5MB em bytes
DATA_UPLOAD_MAX_MEMORY_SIZE = 5242880  # 5MB em bytes

# Formatos de arquivo aceitos para banners (validação adicional no front-end)
ALLOWED_IMAGE_EXTENSIONS = ['.jpg', '.jpeg', '.png', '.gif', '.webp']


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Modelo de usuário customizado
AUTH_USER_MODEL = 'sgea_app.Usuario'

# URLs de redirecionamento
LOGIN_REDIRECT_URL = 'dashboard'
LOGIN_URL = 'login'
LOGOUT_REDIRECT_URL = 'login'

# Formatos de data e hora
DATE_INPUT_FORMATS = [
    '%d/%m/%Y',     # DD/MM/AAAA (padrão brasileiro)
    '%Y-%m-%d',     # AAAA-MM-DD (padrão ISO)
    '%d-%m-%Y',     # DD-MM-AAAA
]

DATETIME_INPUT_FORMATS = [
    '%d/%m/%Y %H:%M',     # DD/MM/AAAA HH:MM
    '%Y-%m-%d %H:%M',     # AAAA-MM-DD HH:MM
    '%Y-%m-%dT%H:%M',     # Formato datetime-local do HTML5
]

# Formato de exibição de data e hora
DATE_FORMAT = 'd/m/Y'
DATETIME_FORMAT = 'd/m/Y H:i'
SHORT_DATE_FORMAT = 'd/m/Y'


# REST Framework Configuration
# https://www.django-rest-framework.org/

REST_FRAMEWORK = {
    # Autenticação obrigatória via Token
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',  # Para o browsable API
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    # Configuração do Throttling (limite de requisições)
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.UserRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'user': '100/day',      # Limite geral por usuário
        'eventos': '20/day',    # Consulta de eventos
        'inscricoes': '50/day', # Inscrições de participantes
    },
    # Paginação padrão
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,
    # Formato de resposta padrão
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ],
    # Parser de requisições
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.FormParser',
        'rest_framework.parsers.MultiPartParser',
    ],
}


# Email Configuration


try:
    from decouple import config
    

    EMAIL_HOST = "smtp.gmail.com"
    EMAIL_PORT = 587
    EMAIL_USE_TLS = True
    EMAIL_HOST_USER = config("EMAIL_HOST_USER", default="placeholder@sgea.com")
    EMAIL_HOST_PASSWORD = config("EMAIL_HOST_PASSWORD", default="senha_placeholder")
    DEFAULT_FROM_EMAIL = EMAIL_HOST_USER


    EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"

except:
   
    EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
    DEFAULT_FROM_EMAIL = "sgea@sistema.com"



# Messages Framework
# https://docs.djangoproject.com/en/5.2/ref/contrib/messages/

from django.contrib.messages import constants as messages

MESSAGE_TAGS = {
    messages.DEBUG: 'info',
    messages.INFO: 'info',
    messages.SUCCESS: 'success',
    messages.WARNING: 'warning',
    messages.ERROR: 'danger',
}


# Security Settings
# Configurações de segurança para produção (ajustar quando for para produção)

if not DEBUG:
    # HTTPS
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    
    # HSTS
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    
    # Content Security
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_BROWSER_XSS_FILTER = True
    X_FRAME_OPTIONS = 'DENY'


# Logging Configuration
# Configuração de logs para auditoria e debugging

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'logs' / 'sgea.log',
            'formatter': 'verbose',
        },
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['file', 'console'],
            'level': 'INFO',
            'propagate': True,
        },
        'sgea_app': {
            'handlers': ['file', 'console'],
            'level': 'DEBUG',
            'propagate': False,
        },
    },
}

# Criar diretório de logs se não existir
LOGS_DIR = BASE_DIR / 'logs'
if not LOGS_DIR.exists():
    LOGS_DIR.mkdir(parents=True, exist_ok=True)


# Custom Settings for SGEA
# Configurações específicas do sistema SGEA

# Tipos de eventos permitidos
TIPOS_EVENTO = [
    ('seminario', 'Seminário'),
    ('palestra', 'Palestra'),
    ('minicurso', 'Minicurso'),
    ('workshop', 'Workshop'),
    ('semana_academica', 'Semana Acadêmica'),
]

# Perfis de usuário
PERFIS_USUARIO = [
    ('aluno', 'Aluno'),
    ('professor', 'Professor'),
    ('organizador', 'Organizador'),
]

# Configurações de certificados
CERTIFICADO_TITULO = 'Sistema de Gestão de Eventos Acadêmicos'
CERTIFICADO_ASSINATURA = 'Coordenação SGEA'

# Tempo de expiração do token de confirmação de email (em horas)
EMAIL_CONFIRMATION_TIMEOUT = 24